# Generated by Django 5.0.6 on 2024-05-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_cloths',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dish_cloth.category'),
        ),
    ]
