# Generated by Django 5.0.6 on 2024-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_cloth', '0002_alter_dish_cloths_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_cloths',
            name='cloth_image',
            field=models.ImageField(blank=True, default='', upload_to='dish_cloth/cloth_images/%d/%m/%Y'),
        ),
    ]
