# Generated by Django 5.0.6 on 2024-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_cloth', '0003_alter_dish_cloths_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_cloths',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
